spring.datasource.url=jdbc:${DATABASE_URL}?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
spring.jpa.show-sql=true


