spring.application.name=urlshortener
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=shivu
spring.datasource.password=Shivu@9019
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
